
trigger:
- feature/avinay

pool: Default

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'avinay'
      backendAzureRmResourceGroupName: 'save'
      backendAzureRmStorageAccountName: 'savesa'
      backendAzureRmContainerName: 'wer'
      backendAzureRmKey: 'ter.tfstate'
  - task: tfsec@1
    inputs:
      version: 'v1.26.0'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'avinay'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'avinay'

